"""
Phase 1 visual dashboard — builds a "Dashboard" sheet inside the same
Excel file generated by export_excel.py, with charts, a heatmap, and a
"card" showing the current reading. Everything is assembled
automatically by Python — you don't need to create any chart manually in
Excel afterward.

Core idea of this file (worth understanding before reading the rest of
the code): an Excel line chart doesn't know how to paint parts of the
SAME line in different colors depending on another column's value (e.g.
"green when regime = Expansion, red when regime = Contraction"). The
trick to get that effect is the `split_by_category` function: instead of
1 column of values, we create N columns (one per category), each filled
in only on the rows where that category is active, and empty (NaN) on
the rest. Excel then receives N series — since they never have data on
the same row, the visual result is a single line that changes color
along with the category. We use this same technique three times in this
file: in the regime chart, in the quadrant (scatter) chart, and in the
tactical risk chart.

On the absence of Excel formulas in this file: unlike an "editable"
financial spreadsheet (where user inputs must propagate via formula),
this dashboard is the output of a Python pipeline that already did all
the calculation — the numbers here are the result of a model, not
assumptions someone will edit later. That's why we write ready-made
values (as the rest of the export already did), instead of recreating
the z-score formulas inside Excel.
"""

import pandas as pd

from openpyxl.chart import LineChart, ScatterChart, Reference, Series
from openpyxl.formatting.rule import ColorScaleRule
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

FONT_NAME = "Calibri"

REGIME_ORDER = ["Expansion", "Recovery", "Slowdown", "Contraction"]
RISK_ORDER = ["Risk-on", "Neutral", "Risk-off"]

REGIME_COLORS = {
    "Expansion": "70AD47",   # green
    "Recovery": "4472C4",    # blue
    "Slowdown": "ED7D31",    # orange
    "Contraction": "C00000", # red
}

RISK_COLORS = {
    "Risk-on": "70AD47",
    "Neutral": "BFBFBF",
    "Risk-off": "C00000",
}

# The tactical risk chart is daily — since 1990 that's ~9,000 points per
# series. Excel can handle it, but the chart gets visually cluttered and
# slow to navigate. That's why we crop it to the last N years here; the
# full history remains available (uncropped) in the Module_B_Daily
# sheet, for anyone who wants to look at the entire period.
RISK_CHART_YEARS = 5


def split_by_category(values: pd.Series, categories: pd.Series, category_order: list) -> pd.DataFrame:
    """
    Turns 1 series of values + 1 series of categories into N columns
    (one per category), each filled in only where that category is
    active. See the full explanation in the module's docstring.

    `values.where(categories == category)` keeps the original value on
    the rows where the condition is true, and replaces it with NaN on
    the rest — it's the "sibling" of `.mask()` (which does the
    opposite).
    """
    return pd.DataFrame({
        category: values.where(categories == category)
        for category in category_order
    })


def build_auxiliary_data(monthly_summary: pd.DataFrame, combined_matrix: pd.DataFrame) -> dict:
    """
    Builds the 3 auxiliary DataFrames the charts will read directly
    (each becomes an auxiliary sheet in Excel):

    1. Aux_Regime — monthly smoothed_score, split by regime, + a
       constant zero reference column (to draw the "neutral level" line
       in the chart).
    2. Aux_Quadrants — smoothed_score (X axis) and momentum split by
       regime (Y axis), for the scatter that visualizes the level x
       momentum classification rule.
    3. Aux_Risk — Module B's daily filtered_score, split by risk,
       cropped to the last RISK_CHART_YEARS years.
    """
    aux_regime = split_by_category(monthly_summary["smoothed_score"], monthly_summary["regime"], REGIME_ORDER)
    aux_regime.insert(0, "zero_reference", 0.0)

    aux_quadrants = pd.DataFrame({"smoothed_score": monthly_summary["smoothed_score"]})
    momentum_by_regime = split_by_category(monthly_summary["momentum"], monthly_summary["regime"], REGIME_ORDER)
    aux_quadrants = aux_quadrants.join(momentum_by_regime)

    cutoff_date = combined_matrix.index.max() - pd.DateOffset(years=RISK_CHART_YEARS)
    recent_matrix = combined_matrix.loc[combined_matrix.index >= cutoff_date]
    aux_risk = split_by_category(recent_matrix["filtered_score"], recent_matrix["risk"], RISK_ORDER)

    return {
        "Aux_Regime": aux_regime,
        "Aux_Quadrants": aux_quadrants,
        "Aux_Risk": aux_risk,
    }


def build_frequency_table(combined_matrix: pd.DataFrame) -> pd.DataFrame:
    """
    Counts how many historical days fell into each of the 12 (regime,
    risk) combinations of the action matrix — organized as a regime x
    risk table, ready to become a heatmap. It's the same question that
    came up when you noticed the odd totals in the pivot table: here you
    can even see the combinations with a zero count (which Excel hid in
    a pivot table based only on the `action` text column).
    """
    table = pd.crosstab(combined_matrix["regime"], combined_matrix["risk"])
    table = table.reindex(index=REGIME_ORDER, columns=RISK_ORDER, fill_value=0)
    return table


# ---------------------------------------------------------------------------
# Chart construction (openpyxl.chart)
# ---------------------------------------------------------------------------

def _regime_line_chart(aux_ws, n_rows) -> LineChart:
    """
    Line chart of the (monthly) regime score, with one series per regime
    (split_by_category technique) + the zero reference line. Since each
    series only has data in the months of "its" regime, the visual
    result is a single line that changes color as the regime changes
    over time.
    """
    chart = LineChart()
    chart.title = "Economic cycle regime — smoothed score (smoothed_score)"
    chart.style = 2
    chart.y_axis.title = "Score (z-score, 3-month moving average)"
    chart.x_axis.title = "Date"
    chart.width, chart.height = 30, 12

    # Columns in the auxiliary sheet: A=date, B=zero_reference, C..F=4 regimes.
    data = Reference(aux_ws, min_col=2, max_col=6, min_row=1, max_row=n_rows + 1)
    chart.add_data(data, titles_from_data=True)
    categories = Reference(aux_ws, min_col=1, min_row=2, max_row=n_rows + 1)
    chart.set_categories(categories)

    colors = ["808080"] + [REGIME_COLORS[r] for r in REGIME_ORDER]
    for series, color in zip(chart.series, colors):
        series.graphicalProperties.line.solidFill = color
        series.graphicalProperties.line.width = 22000  # EMU; ~1.7pt
        series.marker.symbol = "none"
        series.smooth = False

    # The first series (zero_reference) is thinner and dashed, so it
    # doesn't visually compete with the regime series.
    zero_line = chart.series[0].graphicalProperties.line
    zero_line.width = 9000
    zero_line.dashStyle = "sysDash"

    return chart


def _quadrant_chart(aux_ws, n_rows) -> ScatterChart:
    """
    Scatter of smoothed_score (level) x momentum, with one series per
    regime — directly visualizes the 2x2 classification rule (level x
    momentum) from Section 2.2 of the document: each regime should
    occupy a visually separate quadrant from the others.
    """
    chart = ScatterChart()
    chart.title = "Quadrant classification (level x momentum)"
    chart.x_axis.title = "Level score (smoothed_score)"
    chart.y_axis.title = "Momentum"
    chart.style = 13
    chart.width, chart.height = 20, 16

    # The auxiliary sheet has: column A = date (index, written by
    # to_excel), column B = smoothed_score (X axis), columns C..F =
    # momentum split by regime (Y axis, one per series). Point that
    # tripped me up once while testing: the DataFrame's index always
    # "steals" column A when we write with `index_label` — that's why
    # smoothed_score starts at B, not A.
    x_values = Reference(aux_ws, min_col=2, min_row=2, max_row=n_rows + 1)

    # Columns C..F = momentum split by regime (Y axis, one per series).
    for i, regime in enumerate(REGIME_ORDER):
        col = 3 + i
        y_values = Reference(aux_ws, min_col=col, min_row=1, max_row=n_rows + 1)
        series = Series(y_values, x_values, title_from_data=True)
        series.marker.symbol = "circle"
        series.marker.size = 5
        series.marker.graphicalProperties.solidFill = REGIME_COLORS[regime]
        series.marker.graphicalProperties.line.noFill = True
        series.graphicalProperties.line.noFill = True  # points only, no connecting line
        chart.series.append(series)

    return chart


def _risk_line_chart(aux_ws, n_rows) -> LineChart:
    """
    Same technique as the regime chart, applied to Module B's daily
    tactical score (filtered_score), split by risk zone.
    """
    chart = LineChart()
    chart.title = f"Tactical risk (Module B) — last {RISK_CHART_YEARS} years"
    chart.style = 2
    chart.y_axis.title = "Filtered score (-2 to +2)"
    chart.x_axis.title = "Date"
    chart.width, chart.height = 30, 12

    data = Reference(aux_ws, min_col=2, max_col=4, min_row=1, max_row=n_rows + 1)
    chart.add_data(data, titles_from_data=True)
    categories = Reference(aux_ws, min_col=1, min_row=2, max_row=n_rows + 1)
    chart.set_categories(categories)

    for series, risk in zip(chart.series, RISK_ORDER):
        series.graphicalProperties.line.solidFill = RISK_COLORS[risk]
        series.graphicalProperties.line.width = 18000
        series.marker.symbol = "none"
        series.smooth = False

    return chart


# ---------------------------------------------------------------------------
# Heatmap (conditional formatting) and status card
# ---------------------------------------------------------------------------

def _write_heatmap(dashboard_ws, frequency_table: pd.DataFrame, start_row: int, start_col: int):
    """
    Writes the regime x risk table (day count) and applies a 3-point
    `ColorScaleRule` (red → yellow → green) over the values — the native
    Excel/openpyxl way of coloring cells by magnitude, without computing
    any color in Python. A cell with a count of 0 (the Recovery +
    Risk-off combination, which you found) ends up at the red end of the
    scale, clearly visible.
    """
    header_font = Font(name=FONT_NAME, bold=True, color="FFFFFF")
    header_fill = PatternFill("solid", fgColor="404040")

    # Column headers (risk)
    dashboard_ws.cell(row=start_row, column=start_col, value="Regime \\ Risk")
    dashboard_ws.cell(row=start_row, column=start_col).font = header_font
    dashboard_ws.cell(row=start_row, column=start_col).fill = header_fill
    for j, risk in enumerate(RISK_ORDER):
        cell = dashboard_ws.cell(row=start_row, column=start_col + 1 + j, value=risk)
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center")

    # Data rows (regimes)
    for i, regime in enumerate(REGIME_ORDER):
        row = start_row + 1 + i
        label_cell = dashboard_ws.cell(row=row, column=start_col, value=regime)
        label_cell.font = Font(name=FONT_NAME, bold=True)
        for j, risk in enumerate(RISK_ORDER):
            value = int(frequency_table.loc[regime, risk])
            cell = dashboard_ws.cell(row=row, column=start_col + 1 + j, value=value)
            cell.font = Font(name=FONT_NAME)
            cell.alignment = Alignment(horizontal="center")

    # Range with only the numeric values (no headers/labels), which is
    # what ColorScaleRule needs to color.
    first_data_row = start_row + 1
    last_data_row = start_row + len(REGIME_ORDER)
    first_data_col = start_col + 1
    last_data_col = start_col + len(RISK_ORDER)
    cell_range = (
        f"{get_column_letter(first_data_col)}{first_data_row}:"
        f"{get_column_letter(last_data_col)}{last_data_row}"
    )
    rule = ColorScaleRule(
        start_type="min", start_color="F8696B",   # red (lowest count)
        mid_type="percentile", mid_value=50, mid_color="FFEB84",  # yellow (middle)
        end_type="max", end_color="63BE7B",       # green (highest count)
    )
    dashboard_ws.conditional_formatting.add(cell_range, rule)

    return last_data_row  # returns the last row used, to position what comes next


def _write_status_card(dashboard_ws, last_matrix_row: pd.Series, start_row: int, start_col: int):
    """
    Writes a highlighted "card" with the framework's most recent
    reading: date, regime, risk, and recommended action — the
    dashboard's "headline", with a background color matching the current
    regime.
    """
    current_regime = last_matrix_row["regime"]
    background_color = REGIME_COLORS.get(current_regime, "808080")

    label_values = [
        ("Current reading as of", last_matrix_row.name.strftime("%Y-%m-%d")),
        ("Regime (Module A)", current_regime),
        ("Risk (Module B)", last_matrix_row["risk"]),
        ("Recommended action", last_matrix_row["action"]),
    ]

    for i, (label, value) in enumerate(label_values):
        row = start_row + i
        label_cell = dashboard_ws.cell(row=row, column=start_col, value=label)
        label_cell.font = Font(name=FONT_NAME, bold=True, color="FFFFFF")
        label_cell.fill = PatternFill("solid", fgColor="404040")

        value_cell = dashboard_ws.cell(row=row, column=start_col + 1, value=value)
        value_cell.font = Font(name=FONT_NAME, bold=True, size=12, color="FFFFFF")
        value_cell.fill = PatternFill("solid", fgColor=background_color)
        value_cell.alignment = Alignment(horizontal="left", vertical="center", wrap_text=True)

    dashboard_ws.column_dimensions[get_column_letter(start_col)].width = 22
    dashboard_ws.column_dimensions[get_column_letter(start_col + 1)].width = 55

    return start_row + len(label_values)


# ---------------------------------------------------------------------------
# Main function
# ---------------------------------------------------------------------------

def build_dashboard(writer: pd.ExcelWriter, monthly_summary: pd.DataFrame, combined_matrix: pd.DataFrame) -> None:
    """
    This file's "main" function: receives the already-open Excel
    `writer` (the same one used by export_excel.py for the 3 data
    sheets) and adds to it: 3 auxiliary sheets (data prepared for the
    charts) + 1 "Dashboard" sheet (status card, heatmap, and the 3
    charts).

    Needs to be called INSIDE the same `with pd.ExcelWriter(...)` block
    as export_to_excel — it reuses the same `writer`, instead of opening
    the file again, because the `writer` only writes everything to disk
    once the `with` block ends.
    """
    auxiliary_data = build_auxiliary_data(monthly_summary, combined_matrix)
    for sheet_name, df in auxiliary_data.items():
        df.to_excel(writer, sheet_name=sheet_name, index_label="date")

    frequency_table = build_frequency_table(combined_matrix)

    wb = writer.book
    dashboard_ws = wb.create_sheet("Dashboard", 0)  # position 0 = first sheet

    # Current status card, top-left corner.
    next_row = _write_status_card(
        dashboard_ws, combined_matrix.iloc[-1], start_row=2, start_col=2
    )

    # Regime x risk heatmap, right below the card.
    _write_heatmap(dashboard_ws, frequency_table, start_row=next_row + 2, start_col=2)

    # The 3 charts, anchored in cells further right/down so they don't
    # overlap the card and the heatmap.
    aux_ws_regime = wb["Aux_Regime"]
    aux_ws_quadrants = wb["Aux_Quadrants"]
    aux_ws_risk = wb["Aux_Risk"]

    regime_chart = _regime_line_chart(aux_ws_regime, n_rows=len(auxiliary_data["Aux_Regime"]))
    dashboard_ws.add_chart(regime_chart, "H2")

    quadrant_chart = _quadrant_chart(aux_ws_quadrants, n_rows=len(auxiliary_data["Aux_Quadrants"]))
    dashboard_ws.add_chart(quadrant_chart, "B18")

    risk_chart = _risk_line_chart(aux_ws_risk, n_rows=len(auxiliary_data["Aux_Risk"]))
    dashboard_ws.add_chart(risk_chart, "H26")

    # The auxiliary sheets only exist to feed the charts — we hide them
    # so they don't clutter the view for anyone opening the file, but
    # they're still there (and still editable) if you want to check the
    # numbers behind a given chart.
    for sheet_name in auxiliary_data:
        wb[sheet_name].sheet_state = "hidden"

    dashboard_ws.sheet_view.showGridLines = False
